services:
  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.153.0@sha256:3f6d0f8a5ea73fdca126db7ba8ec600994424fb548b54ee95e702673f8d29ba5
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM=us0
      - SPLUNK_HEC_TOKEN
      - SPLUNK_HEC_URL
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "14268:14268" # Jaeger Thrift over HTTP receiver
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
