services:
  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.154.2@sha256:7ca38b306f8736673f24dda39a2c8040d33e575d22054a7f708b5829ea2a21f2
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM=us0
      - SPLUNK_HEC_TOKEN
      - SPLUNK_HEC_URL
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "14268:14268" # Jaeger Thrift over HTTP receiver
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
