services:
  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.157.0@sha256:0f3207d15b8066aa57cd3639944a112901e1050e04dea98676e118427438ab5c
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM=us0
      - SPLUNK_HEC_TOKEN
      - SPLUNK_HEC_URL
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "14268:14268" # Jaeger Thrift over HTTP receiver
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
