receivers:
  otlp:
    protocols:
      grpc:        # used by default
  jaeger:
    protocols:
      thrift_http: # usage: OTEL_TRACES_EXPORTER=jaeger-thrift-splunk OTEL_EXPORTER_JAEGER_ENDPOINT=http://localhost:14268/api/traces

processors:
  batch:

exporters:
  # traces exporters
  logging/traces:
    # logLevel: debug
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace"
  # metrics exporters
  logging/metrics:
    # logLevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    realm: "${SPLUNK_REALM}"

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    traces:
      receivers:
        - otlp
        - jaeger
      processors: [batch]
      exporters:
        - logging/traces
        - otlp
        - sapm
    metrics:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - logging/metrics 
        - prometheus
        - signalfx
