receivers:
  otlp:
    protocols:
      grpc:        # used by default
  jaeger:
    protocols:
      thrift_http: # usage: OTEL_TRACES_EXPORTER=jaeger-thrift-splunk OTEL_EXPORTER_JAEGER_ENDPOINT=http://localhost:14268/api/traces

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace"
  jaeger:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [logging, jaeger, sapm]

  extensions: [health_check, pprof, zpages]
