name: build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
      - name: Build
        run: ./goyek.sh -v -ci
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
      - name: Build
        run: .\goyek.ps1 -v -ci -skip-docker
  macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
      - name: Build
        run: ./goyek.sh -v -ci -skip-docker
