name: goyek

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            run-script: ./goyek.sh -v -ci
        include:
          - os: windows-2019
            run-script: .\goyek.ps1 -v -ci -skip-docker
        include:
          - os: macos-10.15
            run-script: ./goyek.sh -v -ci
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16'
      - run: ${{ run-script }}
      - uses: codecov/codecov-action@v2.0.1
        with:
          files: ./test-results/coverage.out
          flags: ${{ runner.os }}
